---
manager:
  max_workers: 2

providers:
  zones:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones
    default_ttl: 300
    enforce_order: true

  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: 'env/CLOUDFLARE_TOKEN'
    account_id: 'env/CLOUDFLARE_ACCOUNT_ID'

#  route53:
#      class: octodns_route53.Route53Provider
#      access_key_id: 'env/AWS_ACCESS_KEY_ID'
#      secret_access_key: 'env/AWS_SECRET_ACCESS_KEY'

zones:
  example.com.:
      sources:
        - zones
      targets:
        - cloudflare
#        - route53

  example.net.:
      sources:
        - zones
      targets:
        - cloudflare
#        - route53